### ISSUE TITLE
High Token Usage

### ISSUE THREAD

**Issue by TanjimReza** [cline/cline#1030]
### What happened?

For he last few days Cline is using token much higher than it used to before thus resulting in high api usage. 

### Steps to reproduce

1. Cline Chat
2. Claude 3.5 Sonnet
3.

**Comment by saoudrizwan** [comment]
Hey! The higher token count you're seeing is most likely due to your tasks getting long–prompt caching should keep costs low but I suggest starting a new task when you notice requests getting expensive.
Quick tip: Instead of auto-approving everything, try being more hands-on with guiding Cline on which files to read. This usually leads to more focused and efficient token usage. Plus you'll get better results since you know your codebase best.
Let me know if you're still seeing unusually high usage after trying this out! Happy to dig deeper.

**Comment by TanjimReza** [comment]
Hi there!

I am still facing the issue with very simple specific tasks, it was not like this before. Even a simple staticfiles setup is charging $0.5. Specifically mentioned file.
