### ISSUE TITLE
Support for AWS Bedrock Cross-region inference

### ISSUE THREAD

**Issue by ham-zax** [cline/cline#229]
It should be easy to implement as you have the base already, please do asap

**Comment by saoudrizwan** [comment]
Please provide more details, I don't know what you mean

**Comment by cschnidr** [comment]
AWS just introduced cross region inference to load balance requests to Amazon Bedrock automatically. There are currently two options. One for US-based regions and another one for europe based regions (more options coming). You use the converse or the InvokeModel API the same way, but you define your primary region the calls go to and instead of a model-id you use a inference-profile.
```
primary_region ="<primary-region-name>" #us-east-1, eu-central-1
bedrock_runtime = boto3.client("bedrock-runtime", region_name= primary_region)
inferenceProfileId = '<regional-prefix>.anthropic.claude-3-5-sonnet-20240620-v1:0'
```
Check this blog for the long story: https://aws.amazon.com/blogs/machine-learning/getting-started-with-cross-region-inference-in-amazon-bedrock/

**Comment by ham-zax** [comment]
![image](https://github.com/user-attachments/assets/cf43aee2-5f33-4a92-960f-f9c878e27819)
just go through the doc
https://docs.aws.amazon.com/bedrock/latest/userguide/cross-region-inference.html
currently no access is being given to sonnet 3.5 other than cross region, for the past 2 weeks

**Comment by ham-zax** [comment]
@saoudrizwan

**Comment by ham-zax** [comment]
![image](https://github.com/user-attachments/assets/edd84f6f-50a6-4661-8b98-555a36f45598)
Current error when using aws bedrock with cross regioun interface

**Comment by ham-zax** [comment]
@cschnidr any tips to use this with current claude dev, like change some config internally etc

**Comment by cschnidr** [comment]
what is your primary region? When you are using a european region (either eu-central-1, eu-west-1 or eu-west-3) you would use: eu.anthropic.claude-3-5-sonnet-20240620-v1:0 and if you use a US region (either us-east-1 or us-west-2) you would use: us.anthropic.claude-3-5-sonnet-20240620-v1:0 as you model id.
See: https://docs.aws.amazon.com/bedrock/latest/userguide/cross-region-inference-support.html

**Comment by cschnidr** [comment]
@ham-zax see above. You might wanna change the title ASW->AWS

**Comment by anapivirtua** [comment]
+1

EU AWS Bedrock endpoints for Claude are forced to use the recently released cross-region inference(1) to spread load across multiple regions. At the moment claude-dev doesn't support cross-region inference parameter and hence it's not possible anymore to use claude-dev with Bedrock in EU (using direct EU endpoints will lead to HTTP 400 as previously mentioned by @ham-zax).

In the US (e.g., AWS us-east-1 region), using a regional endpoint directly (since not yet enforced to use cross-region inference) often results in HTTP 429 "Too Many Requests" errors. This happens because Bedrock on-demand mode uses a shared capacity pool across customers. ThrottlingExceptions may occur even if you're within the AWS account quota limits and so it's possible to be throttled below expected quota rates.

To improve the situation it will be great if claude-dev can implement a better retry mechanisms with exponential backoff (I'm not sure claude-dev is doing it, leading to need for multiple "retry" manual actions from the user when being throttled) and implement cross-region inference since it's enforced in some regions like EU ones and can help to reduce HTTP 429 via the use of cross-region inference feature.

The doc to leverage inference profiles is here: https://github.com/aws-samples/amazon-bedrock-samples/blob/main/inference/cross-region-inference/Getting_started_with_Cross-region_Inference.ipynb 

Meanwhile my own solution is to use US endpoint (since cross-region inference is not enforced) with provisioned capacity to avoid throttling but that do requires financial commitment and comes with a spending uplift.

(1) https://aws.amazon.com/about-aws/whats-new/2024/09/amazon-bedrock-knowledge-bases-cross-region-inference/

**Comment by cschnidr** [comment]
Sorry the statement that AWS forces cross-region inference in Europe is wrong. This is only true in the Ireland region when your account is not opted-in to use Ireland for Bedrock. The rest of the regions supporting Bedrock in Europe are providing you per default the option to use inference in the specific region or cross-region.

**Comment by anapivirtua** [comment]
You're right, thanks for fixing. Doesn't change the way claude-dev should address this.

**Comment by gao288** [comment]
+1 for too many requests when using US endpoint, on demand tps is not high enough for completing a single question

**Comment by philikai** [comment]
https://github.com/saoudrizwan/claude-dev/pull/432 

Added a PR for fixing this issue.

**Comment by saoudrizwan** [comment]
v2.1.4 now has a cross-region inference toggle that prefixes the model id with the region identifier. Please let me know if this fixes the issue!

![image](https://github.com/user-attachments/assets/0bb80462-88c2-43c7-a991-feed8452969e)
