### ISSUE TITLE
Cline removing the code comments in every line

### ISSUE THREAD

**Issue by cloudbow** [cline/cline#549]
### Which API Provider are you using?

Anthropic

### Which Model are you using?

Claude 3.5 Sonnet

### What happened?

I have asked my code to be edited by providing some context but the cline deleted all the comments.

### Steps to reproduce

1. Just try out any command which causes the file to be edited
2.
3.

**Comment by Purecode24** [comment]
yup, Claude removes comments but (sometimes), it does have a benefit of less files, plus if the code is well written its self documenting, IMHO, I turned off XML commenting (used for documentation in c# etc) until the end of the development cycle. Then, we get less tokens and faster api requests (smaller) and hopefully more expressive code and less noise for Claude to ignore.

**Comment by theviktor** [comment]
I have seen this happen, I always ask it not to remove comments, specially during developmentime its useful for itself, but it wanders off to remove comments when I did not ask it to, like it gets ADHD and gets distracted

**Comment by saoudrizwan** [comment]
Regarding lazy coding `//rest of code here`, there's been an increase in reports about this so I've made the following changes in the latest v2.0.15 that should help mitigate the issue:
1. Adjusted system prompt to keep Cline from doing this as much as possible, but for large enough files it's impossible to force him to output beyond the model's max output token limit. I found that trying to keep him from lazy coding too aggressively would lead to him outputting partial file contents. 
2. When Cline does truncate code you are now alerted by the extension of 'potential code truncation' along with a link to a [troubleshooting guide](https://github.com/cline/cline/wiki/Troubleshooting-%E2%80%90-Cline-Deleting-Code-with-%22Rest-of-Code-Here%22-Comments) to work around the issue.
3. The guide essentially walks you through how to use the diff editor to replace the placeholder comments with the original content. I've also improved the prompts around this so that the model is made aware that the user fixed its response and to proceed accordingly with the new file contents as the baseline.

If it's any consolation, these are temporary measures since Anthropic will soon be releasing a 'Fast Edit Mode' feature to Claude 3.5 Sonnet that will enable faster + more reliable file edits, and hopefully fix this issue for good.

**Comment by Purecode24** [comment]
> I have seen this happen, I always ask it not to remove comments, specially during developmentime its useful for itself, but it wanders off to remove comments when I did not ask it to, like it gets ADHD and gets distracted

Agreed but I'm finding as you automate building the code using Cline you will ask, who is going to use these comments?
I used to think Claude will and it certainly does! Claude puts in place holder and reminders and doesn't take them out, then comments I thought were very informative are later stripped out but I'm less bothered the LLM knows best I find :) 

E.g. I put in "Ignore the warning generated by the following field, its a bug in the preview release and not our code so stop fixing it for the next 6 hours, LOL"

Soon it takes it out and trys to fix that warning, but its early days and Saoud had done an amazing job, but needs Claude to evolved to and the above comment will be great.
