### ISSUE TITLE
'Revert Block' feature doesn't work

### ISSUE THREAD

**Issue by techcow2** [cline/cline#564]
### Which API Provider are you using?

OpenRouter

### Which Model are you using?

Claude 3.5 Sonnet

### What happened?

The revert block feature works up until you click the save button. Then it responds by saying something like "Thank you for showing me the complete code, I'll now provide the complete code..." and then it starts over as if the block wasn't inserted and saved. In summary, if it's actually saving the inserted blocks of missing code, it's telling the API something different.

### Steps to reproduce

1. Click the revert block button
2. Click save
3. Notice that the API still tries working on the file when it shouldn't.

**Comment by saoudrizwan** [comment]
Thank you for bringing this up! It's a hit or miss reproducing this but it certainly did happen. I've adjusted the `write_to_file` tool response so that now it's more clear that the file's contents are updated and the model should course correct accordingly, rather than trying to re-apply the edit. Please update to v2.0.15 and lmk if that fixes the issue for you!

```
pushToolResult(
	`The user made the following updates to your content:\n\n${userEdits}\n\n` +
		`The updated content, which includes both your original modifications and the user's edits, has been successfully saved to ${relPath.toPosix()}. Here is the full, updated content of the file:\n\n` +
		`<final_file_content path="${relPath.toPosix()}">\n${finalContent}\n</final_file_content>\n\n` +
		`Please note:\n` +
		`1. You do not need to re-write the file with these changes, as they have already been applied.\n` +
		`2. Proceed with the task using this updated file content as the new baseline.\n` +
		`3. If the user's edits have addressed part of the task or changed the requirements, adjust your approach accordingly.` +
		`${newProblemsMessage}`
)
```

Feel free to re-open if you're still running into problems.

**Comment by techcow2** [comment]
@saoudrizwan this is working great now! Thank you.
