### ISSUE TITLE
5.4k tokens to say hi?

### ISSUE THREAD

**Issue by M-Gonzalo** [cline/cline#789]
### Which API Provider are you using?

OpenAI

### Which Model are you using?

o1-mini

### What happened?

I told the model hi and it took up 5_400 tokens apparently

### Steps to reproduce

![image](https://github.com/user-attachments/assets/910f89f3-7a16-4e4a-80c8-cfa67de26e6b)

**Comment by MBrekhof** [comment]
Thats no bug, thats your default prompt size. Using Anthropic this at least gets cached.

**Comment by Luxcium** [comment]
i am unsure if the arrows are pointing in the right direction but from my perspective it should be ⬆️Uploading (Request) _from **me** to the model,_ and ⬇️Downloading (Response) _from the **model** to me._

in any case if it is the other way around or not i would be curious to understand the reasoning behind...

but to stay on topic i would be curious to know if you have the same problem with the gpt (rather than an o1) or a claude... and understand what is the token count then?
