### ISSUE TITLE
Unable to grant Cline bulk read permissions to project files

### ISSUE THREAD

**Issue by tentabs00** [cline/cline#896]
### Which API Provider are you using?

Anthropic

### Which Model are you using?

Claude 3.5 Sonnet

### What happened?

I tried to get Cline to grant itself read access to all relevant files in the directory. I was able to give it access to view the filenames, and access to read individual files at once, but not to recursively grant read access to all relevant files. 

### Steps to reproduce

1. tell cline that it needs to read all files in a folder to assess how they work together
2. tell it to grant recursive read permissions
3. no working request is made
[cline_task_dec-11-2024_8-20-44-pm.md](https://github.com/user-attachments/files/18119578/cline_task_dec-11-2024_8-20-44-pm.md)

**Comment by CiberNin** [comment]
This issue can be closed. Cline is working as intended.

Your problem is that there is no such thing as "recursive read permissions"
Cline only has the single file read tool. And it can only read one file at a time (for some reason that has never been explained even though its literally a one line change if you are willing to recompile).
You are only getting errors because cline is trying to use read tool on folder instead of once per each file.

Just check the setting to auto-approve read operations.

**Comment by saoudrizwan** [comment]
@CiberNin is right, it's currently not possible for cline to bulk read files. You can work around this by using '@' file names in the input. I've avoided added bulk reading since it's led to Cline re-reading files often leading to much higher token usage than if it methodically reads one file at a time and thinks about the contents before moving on to the next file to read. I've found having the file contents separated into individual messages rather than having multiple files in a single user message keeps the model from wanting to re-read the file over and over again.

I will work on adding bulk reading with the proper promping to avoid this re-reading behavior, hope to have it in asap
