### ISSUE TITLE
Stuck in Loops

### ISSUE THREAD

**Issue by pageagency** [cline/cline#949]
### Which API Provider are you using?

OpenRouter

### Which Model are you using?

Sonnet 3.5

### What happened?

In the last week or so it gets stuck in loops were is will create a situation in which it needs to hold two or more files in context to be able to complete a task.  It doesn't seem to be able to do this anymore.  A few examples are. 
- needs to remove a conflicting file, removes file, can't find file it just removed, needs to create file, file creates conflict. 
- Needs to create matching nonce . Creates a file with nonce, needs to create the matching key in other file, updates other file, key doesn't match, update original, doesn't match either, goes round and round until cancelled. 

Adding more than two files exacerbates the issue. 

### Steps to reproduce

1. You r guess is as good as mine. 
2.
3.

**Comment by pageagency** [comment]
I would also generally like to know why preprmopt don't work and why instructions barely work. my preprompts are basically variations of "DO NOT CODE" "DO NOT RESPOND WITH CODE", but it just starts running anyways. I then hit cancel and start typing and it starts coding again. I then hit cancel a bunch more times then I write again "DO NOT RESPOSND WITH CODE" , it wil start saying you are absolutely right, i need to understand the issue before i start coding, then start coding. 

and then there are things like this as well:
![image](https://github.com/user-attachments/assets/6a2adfe5-5a1b-4f47-a090-90e6028985c7)

**Comment by Recuba** [comment]
> I would also generally like to know why preprmopt don't work and why instructions barely work. my preprompts are basically variations of "DO NOT CODE" "DO NOT RESPOND WITH CODE", but it just starts running anyways. I then hit cancel and start typing and it starts coding again. I then hit cancel a bunch more times then I write again "DO NOT RESPOSND WITH CODE" , it wil start saying you are absolutely right, i need to understand the issue before i start coding, then start coding.
> 
> and then there are things like this as well: ![image](https://private-user-images.githubusercontent.com/376419/397198701-6a2adfe5-5a1b-4f47-a090-90e6028985c7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1ODM4MzgsIm5iZiI6MTczNDU4MzUzOCwicGF0aCI6Ii8zNzY0MTkvMzk3MTk4NzAxLTZhMmFkZmU1LTVhMWItNGY0Ny1hMDkwLTkwZTYwMjg5ODVjNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxOVQwNDQ1MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xOTgwMjc5ZjJmMTIwYWFmZGFkZjg3YWI1YTEwOWNmMmM4NWE2NjhiOTRlZWE0Y2JhZjgxMDA3YmI5YWQyYTJlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.LF1EIKiXi7YbQc63K2cleqxpmgp2RXkBepTi4468H7Q)
> 
> One last thing. There is an approval process for reading files, what about editing files? Can we switch those? I know you can accept or reject, but I think it would be useful to see what the intention is before it even starts rather than getting the new code and the intention at the same time and no chance to comment or redirect before the tokens are spent.

YES, custom instructions are a joke! if you, if you're not capable of configuring your code to make it work as it should then remove it and fix it under the hood! @saoudrizwan This is not a new issue and you know that since the inception of Claude Dev! its been almost a year and you cannot figure out how make the extension to comply with the custom instructions that's completely fine and thank you so much for this wonderful extension but remove the custom instructions feature as it doesn't work and you crossed the 5 month issue rule, therefore its considered misleading advertisement under the FTCA  "unfair or deceptive acts or practices in or affecting commerce."

**Comment by saoudrizwan** [comment]
Unfortunately seems like a model being stupid problem, and something I wish I could fix with the right prompting. Any help here would be appreciated, specifically with getting Cline to respect custom instructions regularly rather than only at the beginning of a task. This could be as simple as "Don't forget the user's custom instructions" at the end of each user message

**Comment by saoudrizwan** [comment]
I apologize for the frustration this has caused. I'm going to close this issue for now since there are quite a few duplicates related to this, but please know I will try to figure this out and make Cline better about respecting custom instructions.
