### ISSUE TITLE
Output horizonallty truncated when using Gemini

### ISSUE THREAD

**Issue by ichoosetoaccept** [cline/cline#967]
### Which API Provider are you using?

OpenRouter

### Which Model are you using?

gemini-exp-1206

### What happened?

It works but the model output is truncated horizontally. Word wrapping should be enabled.

### Steps to reproduce

1. Use the model for anything
2. Observe:

![CleanShot 2024-12-20 at 11 33 49@2x](https://github.com/user-attachments/assets/37af5118-f69e-46cf-a1b1-bd3148f45871)

**Comment by saoudrizwan** [comment]
This is unfortunate–the model is outputting content in code blocks. Likely because you're using a weaker model, and not something I can fix on my end since there may be legitimate cases a stronger model wants to output a code block. I suggest in Settings > Custom Instructions, adding "Do not use markdown triple backticks ``` in your responses"
