### ISSUE TITLE
413 Request body too large for meta-llama-3-70b-instruct model. Max size: 8000 tokens.

### ISSUE THREAD

**Issue by ioud8hfi** [cline/cline#995]
### What happened?

I entered my GitHub API key, selected the right model, but it said the message was too long—over 8,000 tokens. However, I only sent a single character "0." I have searched for a long time, but nothing useful came up. Any ideas? Thanks a bunch!
![image](https://github.com/user-attachments/assets/be6f8cfe-0c0b-4748-8d88-d43daf4eb810)
![image](https://github.com/user-attachments/assets/75f7291e-b4e4-408c-b2da-a9dbb00c6d20)

### Steps to reproduce

1. Click on Settings
2. Switch API Provider to OpenAI Compatible 
3. Set up the model's API and name.

**Comment by torxtor** [comment]
it's appears to be a limitation of the model provider

**Comment by saoudrizwan** [comment]
The system prompt alone is fairly large, but there's some initial context about your workspace that gets sent up along with the "0" you sent which is why you're seeing this happen. Unfortunately @torxtor is right, the API you're using is super limited so I suggest using OpenRouter + Claude 3.5 Sonnet instead!
